version: "3"

services:
  web:
    image: nginx
    container_name: "${PROJECT_NAME}_nginx"
    volumes:
      - "./web:/var/www/html"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
    ports:
      - 8002:80

  drupal:
    image: drupal:8.6-fpm-alpine
    container_name: "${PROJECT_NAME}_drupal"
    volumes:
      - "./web:/var/www/html"
    restart: always
    depends_on:
      - mysql

  mariadb:
      image: mariadb
      container_name: "${PROJECT_NAME}_mysql"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: drupal
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: drupal
      volumes:
        - "./docker/mariadb:/var/lib/mysql"
      restart: always